apiVersion: apps/v1
kind: Deployment
metadata:
  name: benthos-api-gateway
  namespace: default
  labels:
    app: benthos-api-gateway
    component: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: benthos-api-gateway
  template:
    metadata:
      labels:
        app: benthos-api-gateway
        component: api-gateway
    spec:
      containers:
      - name: benthos
        image: jeffail/benthos:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4195
          name: http
        - containerPort: 9090
          name: metrics
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        volumeMounts:
        - name: config
          mountPath: /benthos
        env:
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: redis-credentials
              key: url
        - name: POSTGRES_DSN
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: dsn
        - name: RABBITMQ_URL
          valueFrom:
            secretKeyRef:
              name: rabbitmq-credentials
              key: url
        - name: LOG_LEVEL
          value: "INFO"
        livenessProbe:
          httpGet:
            path: /ping
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: config
        configMap:
          name: benthos-api-gateway-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: benthos-api-gateway-config
  namespace: default
# The actual config data will be generated by kustomize
# from the files in config/benthos/
---
apiVersion: v1
kind: Service
metadata:
  name: benthos-api-gateway
  namespace: default
spec:
  selector:
    app: benthos-api-gateway
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: metrics
    port: 9090
    targetPort: metrics
  type: ClusterIP 