apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-gateway.yaml
  - ml-worker.yaml
  - results-collector.yaml
  # Add other resources here if needed

configMapGenerator:
  # API Gateway ConfigMap
  - name: benthos-api-gateway-config
    files:
      - api-gateway.yaml=../../config/benthos/api-gateway/config.yaml
      - common/redis.yaml=../../config/benthos/common/redis.yaml
      - common/sql.yaml=../../config/benthos/common/sql.yaml
      - common/quota.yaml=../../config/benthos/common/quota.yaml
      - common/observability.yaml=../../config/benthos/common/observability.yaml
  
  # ML Worker ConfigMap
  - name: benthos-ml-worker-config
    files:
      - config.yaml=../../config/benthos/ml-worker/config.yaml
      - common/sql.yaml=../../config/benthos/common/sql.yaml
      - common/observability.yaml=../../config/benthos/common/observability.yaml 

  # Results Collector ConfigMap
  - name: benthos-results-collector-config
    files:
      - config.yaml=../../config/benthos/results-collector/config.yaml
      - common/sql.yaml=../../config/benthos/common/sql.yaml
      - common/observability.yaml=../../config/benthos/common/observability.yaml
