apiVersion: apps/v1
kind: Deployment
metadata:
  name: benthos-ml-worker
  labels:
    app: benthos-ml-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: benthos-ml-worker
  template:
    metadata:
      labels:
        app: benthos-ml-worker
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "4196"
    spec:
      containers:
      - name: benthos
        image: jeffail/benthos:4.21
        ports:
        - containerPort: 4196
        volumeMounts:
        - name: config
          mountPath: /benthos
        env:
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: redis-credentials
              key: url
        - name: RABBITMQ_URL
          valueFrom:
            secretKeyRef:
              name: rabbitmq-credentials
              key: url
        - name: POSTGRES_DSN
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: dsn
        - name: ML_SERVICE_URL
          value: http://ml-inference:8080
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /ping
            port: 4196
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 4196
          initialDelaySeconds: 5
          periodSeconds: 10
      volumes:
      - name: config
        configMap:
          name: benthos-ml-worker-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: benthos-ml-worker-config
# The actual config data will be generated by kustomize
# from the files in config/benthos/
---
apiVersion: v1
kind: Service
metadata:
  name: benthos-ml-worker
  labels:
    app: benthos-ml-worker
spec:
  ports:
  - port: 4196
    targetPort: 4196
    protocol: TCP
    name: http
  selector:
    app: benthos-ml-worker 