apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ml-worker-scaler
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: benthos-ml-worker
  pollingInterval: 15
  cooldownPeriod: 30
  minReplicaCount: 1
  maxReplicaCount: 20
  triggers:
  - type: rabbitmq
    metadata:
      mode: QueueLength
      queueName: ml_requests
      hostFromEnv: RABBITMQ_HOST
      protocol: amqp
      value: "5"  # Scale up when there are 5 or more messages in the queue
    authenticationRef:
      name: rabbitmq-trigger-auth
---
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: rabbitmq-trigger-auth
  namespace: default
spec:
  secretTargetRef:
  - parameter: host
    name: rabbitmq-connection
    key: host
  - parameter: username
    name: rabbitmq-connection
    key: username
  - parameter: password
    name: rabbitmq-connection
    key: password
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-connection
  namespace: default
type: Opaque
stringData:
  host: amqp://rabbitmq.data-infra.svc.cluster.local:5672
  username: user
  password: your-secure-password
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ml-worker-token-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: benthos-ml-worker
    kind: Deployment
  minReplicaCount: 1
  maxReplicaCount: 10
  pollingInterval: 15
  cooldownPeriod: 30
  triggers:
    - type: prometheus
      metadata:
        serverAddress: http://prometheus-server.monitoring.svc.cluster.local
        metricName: ml_tokens_processed_rate
        query: sum(rate(ml_tokens_processed_total{type="prompt"}[5m])) * 60
        threshold: "5000"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ml-service-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: ml-inference
    kind: Deployment
  minReplicaCount: 1
  maxReplicaCount: 5
  pollingInterval: 15
  cooldownPeriod: 30
  triggers:
    - type: cpu
      metadata:
        type: Utilization
        value: "70" 