apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: persistent-database

resources:
  - liquibase-config.yaml
  - liquibase-job.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: liquibase-changelogs
    files:
      - changelogs/master.yaml
      - changelogs/001-create-inference-requests.yaml
