apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: persistent-database
type: Opaque
stringData:
  username: mladmin
  password: mysupersecurepassword
---
apiVersion: v1
kind: Secret
metadata:
  name: superuser-secret
  namespace: persistent-database
type: kubernetes.io/basic-auth
stringData:
  username: postgres
  password: P0stgresS3cr3t
