apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: ml-inference
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7.0-alpine
        ports:
        - containerPort: 6379
          name: redis
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          tcpSocket:
            port: 6379
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - redis-cli
            - ping
          initialDelaySeconds: 5
          periodSeconds: 5
        command:
        - redis-server
        - --appendonly
        - "yes"
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: ml-inference
spec:
  selector:
    app: redis
  ports:
  - port: 6379
    targetPort: 6379
    name: redis
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-init
  namespace: ml-inference
data:
  init.redis: |
    # Set the daily quota for default user
    HSET user:default-user:quota:daily:tokens limit 10000
    HSET user:default-user:quota:daily:tokens used 0
    HSET user:default-user:quota:daily:requests limit 100  
    HSET user:default-user:quota:daily:requests used 0
    
    # Set the monthly quota for default user
    HSET user:default-user:quota:monthly:tokens limit 100000
    HSET user:default-user:quota:monthly:tokens used 0
    HSET user:default-user:quota:monthly:requests limit 1000
    HSET user:default-user:quota:monthly:requests used 0 