apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: default
type: Opaque
stringData:
  dsn: postgres://postgres:your-secure-password@postgresql.data-infra.svc.cluster.local:5432/mlservice
  username: postgres
  password: your-secure-password
---
apiVersion: v1
kind: Secret
metadata:
  name: redis-credentials
  namespace: default
type: Opaque
stringData:
  url: redis://redis.data-infra.svc.cluster.local:6379
  password: your-secure-password
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: default
type: Opaque
stringData:
  url: amqp://user:your-secure-password@rabbitmq.data-infra.svc.cluster.local:5672/
  username: user
  password: your-secure-password 