# KEDA ScaledObject for ML Worker
# 
# This configuration enables auto-scaling of the ML Worker deployment
# based on the number of messages in the RabbitMQ queue.
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ml-worker-scaler
  labels:
    app: ml-worker
spec:
  scaleTargetRef:
    name: ml-worker
    kind: Deployment
  minReplicaCount: 1
  maxReplicaCount: 10
  pollingInterval: 15
  cooldownPeriod: 30
  triggers:
  - type: rabbitmq
    metadata:
      protocol: amqp
      queueName: ml-requests
      mode: QueueLength
      value: "5"
      host: amqp://user:$(RABBITMQ_PASSWORD)@rabbitmq.$(NAMESPACE).svc.cluster.local:5672/
    authenticationRef:
      name: rabbitmq-trigger-auth
---
# KEDA TriggerAuthentication for RabbitMQ
apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: rabbitmq-trigger-auth
spec:
  secretTargetRef:
  - parameter: RABBITMQ_PASSWORD
    name: rabbitmq-credentials
    key: password
  - parameter: NAMESPACE
    name: rabbitmq-credentials
    key: namespace 