apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-inference
  namespace: default
  labels:
    app: ml-inference
    component: ml-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ml-inference
  template:
    metadata:
      labels:
        app: ml-inference
        component: ml-service
    spec:
      containers:
      - name: ml-inference
        image: ml-inference:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 9090
          name: metrics
        resources:
          requests:
            cpu: 500m
            memory: 2Gi
          limits:
            cpu: 2
            memory: 8Gi
        env:
        - name: MODEL_PATH
          value: "/models/model.bin"
        - name: LOG_LEVEL
          value: "INFO"
        - name: MAX_BATCH_SIZE
          value: "4"
        - name: MAX_TOKENS
          value: "2048"
        volumeMounts:
        - name: models
          mountPath: /models
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: models
        persistentVolumeClaim:
          claimName: ml-models-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: ml-inference
  namespace: default
spec:
  selector:
    app: ml-inference
  ports:
  - name: http
    port: 8000
    targetPort: http
  - name: metrics
    port: 9090
    targetPort: metrics
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ml-models-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard 