{{- if .Values.externalServices }}
apiVersion: v1
kind: Secret
metadata:
  name: bento-external-services
  labels:
    {{- include "bento-stack.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.externalServices.rabbitmq }}
  RABBITMQ_URL: {{ .Values.externalServices.rabbitmq.url | b64enc | quote }}
  {{- end }}
  {{- if .Values.externalServices.redis }}
  REDIS_URL: {{ .Values.externalServices.redis.url | b64enc | quote }}
  {{- end }}
  {{- if .Values.externalServices.postgres }}
  POSTGRES_DSN: {{ .Values.externalServices.postgres.dsn | b64enc | quote }}
  {{- end }}
  {{- if .Values.externalServices.notification }}
  NOTIFICATION_URL: {{ .Values.externalServices.notification.url | b64enc | quote }}
  {{- end }}
  {{- if .Values.externalServices.ml_service }}
  ML_SERVICE_URL: {{ .Values.externalServices.ml_service.url | b64enc | quote }}
  {{- end }}
{{- end }} 